### ISSUE TITLE
Error when trying to build in cygwin

### ISSUE THREAD

**Issue by whiggs** [AbiWord/uspell#1]
Hello sir.  So I am pretty new to building projects like this from source, but have been able to achieve a few successes.  However, when I clone the git repository for uspell and follow the instructions from within cygwin, I get all the way to running "make".  After I run make, the attached picture is what I receive.  Any advice on how to successfully build on Windows?
[http://i.imgur.com/nHBVtGp.png](url)
![image](https://user-images.githubusercontent.com/11139575/26857345-f688ded0-4af7-11e7-9bb1-fda74419f411.png)

**Comment by hfiguiere** [comment]
Pull the latest changes I just pushed (sorry about that I had forgotten about them). It should be working better.

**Comment by whiggs** [comment]
Ah yes...  That was much more successful.  Issue resolved.  Thanks
